name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 17 * * 4'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: jvm
          - name: js
          - name: native
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: adopt
    - uses: coursier/cache-action@v6
    - run: |
        case "${{ matrix.name }}" in
          "jvm")
            sbt -v "+ applybuilderJVM/test"
            ;;
          "js")
            sbt -v "+ applybuilderJS/test"
            ;;
          "native")
            sbt -v "+ applybuilderNative/test"
            ;;
          *)
            echo "unknown job name"
            exit 1
        esac
        rm -rf "$HOME/.ivy2/local" || true
